# Generated by Django 4.2.1 on 2023-06-05 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.account')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
            bases=('blog.account',),
        ),
    ]
